# netlify.toml

[build]
  functions = "netlify/functions"  # Path to your serverless functions

[[redirects]]
  from = "/old-url"
  to = "/new-url"
  status = 301

# Function Timeout Configuration
[functions]
  max_duration = 26  # Maximum duration for functions in seconds (max 26 for free plan)
